### 
# @name validOrder
POST http://localhost:3000/order
Content-Type: application/x-www-form-urlencoded

type=offer&price=175&quantity=100

### 
# @name invalidOrder
POST http://localhost:3000/order
Content-Type: application/x-www-form-urlencoded

type=Invalid&price=300&quantity=3

### 
# @name createOffer
POST http://localhost:3000/order
Content-Type: application/x-www-form-urlencoded

type=OFfEr&price=171&quantity=1

### 
# @name createBid
POST http://localhost:3000/order
Content-Type: application/x-www-form-urlencoded

type=BiD&price=180&quantity=300

###
# @name getTrades
GET http://localhost:3000/trades
Content-Type: application/x-www-form-urlencoded