name: Node.js CI

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
    paths-ignore:
      - '!**' # Include all paths

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if pull request was merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: echo "Pull request was merged, triggering build"
        
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
